# GitHub Pages Configuration

# Custom 404 page
404.html

# Security headers (handled by workflow and build process)
# See .github/workflows/deploy.yml for security configurations

# Assets that should be cached
*.js
*.css
*.png
*.svg
*.ico
*.woff
*.woff2

# Cache control for different file types
- url: /assets/*.js
  headers:
    Cache-Control: public, max-age=31536000, immutable
    
- url: /assets/*.css
  headers:
    Cache-Control: public, max-age=31536000, immutable

- url: /assets/*.png
  headers:
    Cache-Control: public, max-age=31536000

- url: /assets/*.svg
  headers:
    Cache-Control: public, max-age=31536000

# Security headers
- url: /*
  headers:
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Referrer-Policy: strict-origin-when-cross-origin
    Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; font-src 'self'; object-src 'none'; media-src 'none'; frame-src 'none';